version: "3.7"

services: 
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - traefik_default
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 9091:9091
    environment:
      - PUID=${UID}
      - PGID=${UID}
      - TZ=${TZ}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD} 
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_RATIO_LIMIT=0.50
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_BLOCKLIST_URL=""
      - TRANSMISSION_BLOCKLIST_ENABLED=false
      - TRANSMISSION_DOWNLOAD_DIR="/downloads"
      - TRANSMISSION_INCOMPLETE_DIR="/downloads/incomplete"
      - TRANSMISSION_WATCH_DIR="/downloads/watch"
      - TRANSMISSION_HOME="/config"
      # - LOCAL_NETWORK=${LOCAL_NETWORK}
    volumes:
      - ./storage/docker/transmission:/config
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - traefik_default
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - ./storage/docker/sonarr:/config
      - ${DOWNLOADS_FOLDER}:/downloads
      - ${TVSERIES_FOLDER}:/tv
    environment:
      - PUID=${UID}
      - PGID=${UID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - transmission

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - traefik_default
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - ./storage/docker/radarr:/config
      - ${DOWNLOADS_FOLDER}:/downloads
      - ${MOVIES_FOLDER}:/movies
    environment:
      - PUID=${UID}
      - PGID=${UID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - transmission

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    networks:
      - traefik_default
    ports:
      - 9117:9117
    volumes:
      - ./storage/docker/jackett/:/config/Jackett
      - ${DOWNLOADS_FOLDER}:/downloads
    environment:
      - PUID=${UID}
      - PGID=${UID}
      - TZ=${TZ}
    restart: unless-stopped

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    networks:
      - traefik_default
    environment:
      - PUID=${UID}
      - PGID=${UID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
    ports:
      - 32400:32400
    volumes:
      - ${MOVIES_FOLDER}:/data/movies
      - ${TVSERIES_FOLDER}:/data/tvshows
      - /tmp:/tmp
    # devices:
      # - /dev/dri:/dev/dri
    restart: unless-stopped

networks: 
  traefik_default:
    external: true