name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    # Caching
    - name: Composer Cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: '**/vendor'
        key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

    # Commands
    - name: Setup .env
      run: cp .env.github .env

    - name: Docker create network
      run: docker network create traefik_default

    - name: Docker start
      run: docker-compose up -d laravel

    - name: Composer install
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: docker-compose exec -T laravel composer install --no-dev

    - name: Format PHP
      run: docker-compose exec -T laravel composer format-php-dry

    - name: Statically Analyze PHP
      run: docker-compose exec -T laravel composer larastan
      
    # TODO tests / DB stuff?